baseURL = "http://tjgao.github.com/"
languageCode = "zh-cn"
title = "tj's blog"
theme = "hugo-theme-minos"

[Taxonomies]
	tag = "tags"
	category = "categories"

[params]
	smartToc = true
	disqusShortname = "tiejun"
	googleAnalytics = "UA-33645611-1"
